baseURL: http://{BASE_URL}/
languageCode: en-us
title: Welcome to Gen3
SectionPagesMenu: mainmenu
enableEmoji: true

# for local testing if using Hugo > 0.60.0
# see https://gohugo.io/news/0.60.0-relnotes/
markup:
  goldmark:
    renderer:
      unsafe: true

# allow running `asciidoctor` to parse `asciidoc` files
security:
  exec:
    allow:
    - asciidoctor

menu:
  mainmenu:
    - identifier: about
      name: About
      url: /
      hasChildren: true
      weight: 10
    - identifier: powered-by-gen3
      name: Powered by Gen3
      url: /powered-by-gen3
      parent: about
      weight: 101
    - identifier: gen3-tools
      name: Gen3 Tools
      url: /gen3-tools
      parent: about
      weight: 102
    - identifier: ga4gh
      name: GA4GH Standards
      url: /ga4gh
      parent: about
      weight: 103
    - identifier: gen3refs
      name: Gen3 References
      url: /gen3refs
      parent: about
      weight: 104
    - identifier: products
      name: Products
      url: /products/
      hasChildren: true
      weight: 20
    - identifier: products/data-hub
      name: Data Hubs
      url: /products/data-hubs
      parent: products
      weight: 203
    - identifier: products/data-meshes
      name: Data Meshes
      url: /products/data-meshes
      parent: products
      weight: 202
    - identifier: products/mesh-services
      name: Mesh Services
      url: /products/mesh-services
      parent: products
      weight: 204
    - identifier: products/data-commons
      name: Data Commons
      url: /products/data-commons
      parent: products
      weight: 201
    - identifier: products/workspaces
      name: Workspaces
      url: /products/workspaces
      parent: products
      weight: 204
    - identifier: user_guide
      name: User Guide
      url: https://docs.gen3.org/
      hasChildren: false
      weight: 60
    - identifier: community
      name: Community
      url: /community/
      hasChildren: true
      weight: 50
    - identifier: community/events
      name: Events
      url: /community/events
      parent: community
      weight: 501
    - identifier: community/tutorials
      name: Tutorials
      url: /community/tutorials
      parent: community
      weight: 501
    - identifier: governance
      name: Gen3 Governance
      url: /governance/
      parent: community
      weight: 502
    - identifier: working-groups
      name: Gen3 Working Groups
      url: /working-groups/
      parent: community
      weight: 503
    - identifier: support-orgs
      name: Gen3 Support Organizations
      url: /support-orgs/
      parent: community
      weight: 504
    - identifier: community/slack
      name: Join us on Slack!
      url: https://docs.google.com/forms/d/e/1FAIpQLSczyhhOXeCK9FdVtpQpelOHYnRj1EAq1rwwnm9q6cPAe5a7ug/viewform
      parent: community
      weight: 505
    - identifier: community/discussion_board
      name: Discussion Board
      url: https://forums.gen3.org/
      parent: community
      weight: 506
    # - identifier: /community/medium
    #   name: Medium
    #   url: /community/medium/
    #   parent: community
    #   weight: 502
  footermenu1:
    - identifier: about
      name: About
      url: /
      weight: 1
    - identifier: community
      name: Community
      url: /community
      weight: 2
    - identifier: why
      name: Why Gen3
      url: /products/
      weight: 3
    - identifier: demo
      name: Demo
      url: https://gen3.datacommons.io
      weight: 4
  footermenu2:
    - identifier: powered-by-gen3
      name: Powered by Gen3
      url: /powered-by-gen3
      weight: 1
    - identifier: run-commons
      name: Run a Gen3 commons
      url: https://docs.gen3.org/gen3-resources/operator-guide/
      weight: 2
    - identifier: submit-data
      name: Submit data to a commons
      url: https://docs.gen3.org/gen3-resources/operator-guide/submit-structured-data/
      weight: 3
    - identifier: access-data
      name: Access data in a commons
      url: https://docs.gen3.org/gen3-resources/user-guide/access-data/
      weight: 4
    - identifier: build-app
      name: Build an app for Gen3
      url: /https://docs.gen3.org/gen3-resources/user-guide/using-api/
      weight: 5
params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  logo:
    src: /img/logos/gen3_new_logo_white.svg
    alt: Gen3 Data Commons Logo
  mobileLogo:
    src: /img/logos/gen3_new_logo.png
    alt: Gen3 Data Commons Logo
  icons:
    cross:
      src: /img/icons/x.svg
    toggleDown:
      src: /img/icons/toggle-down.svg
    toggleRight:
      src: /img/icons/toggle-right.svg
    menu:
      src: /img/icons/menu.svg
    externalLink:
      src: /img/icons/external-link.svg
  submenu:
    - identifier: resources/gen3-features
      name: Gen3 Features
      parent: resources
      url: /resources/gen3-features
    - identifier: /resources/user
      name: Gen3 User Guide
      parent: resources
      url: /resources/user/
    - identifier: /resources/developer
      name: Gen3 Developer
      parent: resources
      url: /resources/developer/
    - identifier: /resources/operator
      name: Gen3 Operator - Set up Gen3
      parent: resources
      url: /resources/operator/
    - identifier: resources/faq
      name: Frequently Asked Questions
      parent: resources
      url: /resources/faq/
  developerMenu:
    title: Gen3 Developers Content
    content:
      - category: Gen3 Technology
        content:
          - name: Technical Intro
            link: /resources/developer/
            submenu:
              - name: Terminology
                link: /resources/developer/#terminology
              - name: Data management
                link: /resources/developer/#data-management
              - name: Workspace Systems
                link: /resources/developer/#workspace-systems
          - name: Microservices
            link: /resources/developer/microservice/
      - category: Tutorials
        content:
          - name: Build Apps on Gen3
            link: /resources/developer/build-app/
            submenu:
              - name: 1. Authentication
                link: /resources/developer/build-app/#1-authentication
              - name: 2. GraphQL Queries
                link: /resources/developer/build-app/#2-graphql-queries
              - name: 3. GraphQL Queries You Want To Run
                link: /resources/developer/build-app/#3-graphql-queries-you-want-to-run
              - name: 4. Retrieve The Dictionary JSON Schema
                link: /resources/developer/build-app/#4-retrieve-the-dictionary-json-schema
          - name: Gen3 Queries
            link: /resources/developer/flat-model-api/
  operatorMenu:
    title: Gen3 Operators
    content:
      - category: Running Commons
        content:
          - name: Gen3 On Helm
            link: /resources/operator/#1-gen3-on-helm
          - name: Cloud Automation
            link: /resources/operator/#2-cloud-automation
          - name: Creating a New Data Dictionary
            link: /resources/operator/#3-creating-a-new-data-dictionary
          - name: Dictionary Update Documentation
            link: /resources/operator/#4-dictionary-update-documentation
          - name: Authentication Methods
            link: /resources/operator/#5-authentication-methods
          - name: Programs and Projects
            link: /resources/operator/#6-programs-and-projects
          - name: How to Upload and Control File Access via authz
            link: /resources/operator/#7-how-to-upload-and-control-file-access-via-authz
          - name: ETL and Data Explorer Configurations
            link: /resources/operator/#8-etl-and-data-explorer-configurations
          - name: Gen3 Portal Configurations Examples
            link: /resources/operator/#9-gen3-portal-configurations-examples

  userMenu:
    title: Gen3 Users
    content:
      - category: Users
        content:
          - name: User Guide Overview
            link: /resources/user
          - name: Access and Explore Metadata/Data Files
            link: /resources/user/access-data/
            submenu:
              - name: Access Data from the Data Commons Website
                link: /resources/user/access-data/#access-data-from-the-data-commons-website
              - name: Access Data using the API
                link: /resources/user/access-data/#access-data-using-the-api
          - name: Analyze Data
            link: /resources/user/analyze-data/
            submenu:
              - name: Launch Workspace
                link: /resources/user/analyze-data/#1-launch-workspace
              - name: Getting Files into the Gen3 Workspace
                link: /resources/user/analyze-data/#2-getting-files-into-the-gen3-workspace
              - name: Working with the proxy and allow lists
                link: /resources/user/analyze-data/#3-working-with-the-proxy-and-allow-lists
              - name: Using the Gen3 Python SDK
                link: /resources/user/analyze-data/#4-using-the-gen3-python-sdk
              - name: Jupyter Notebook Demos
                link: /resources/user/analyze-data/#5-jupyter-notebook-demos
          - name: Guide for Data Contributions
            link: /resources/user/submit-data/
            submenu:
              - name: Prepare Project in Submission Portal
                link: /resources/user/submit-data/#1-prepare-project-in-submission-portal
              - name: Upload Data Files to Object Storage
                link: /resources/user/submit-data/#2-upload-data-files-to-object-storage
              - name: Map Uploaded Files to a Data File Node
                link: /resources/user/submit-data/#3-map-uploaded-files-to-a-data-file-node
              - name: Submit Additional Project Metadata
                link: /resources/user/submit-data/#4-submit-additional-project-metadata
              - name: Link Data File Records to their Metadata Records
                link: /resources/user/submit-data/#5-link-files-to-their-metadata
          - name: TSV Formatting and Templates
            link: /resources/user/template-tsvs/
            submenu:
              - name: TSV Formatting Checklist
                link: /resources/user/template-tsvs/#tsv-formatting-checklist
              - name: Notes about TSV Formatting
                link: /resources/user/template-tsvs/#notes-about-tsv-formatting
              - name: Template TSVs for Metadata Submission
                link: /resources/user/template-tsvs/#template-tsvs-for-metadata-submission
          - name: Upload/Download Data Files Using the Gen3-Client
            link: /resources/user/gen3-client/
            submenu:
              - name: Installation Instructions
                link: /resources/user/gen3-client/#1-installation-instructions
              - name: Configure a Profile
                link: /resources/user/gen3-client/#2-configure-a-profile-with-credentials
              - name: Upload Data Files
                link: /resources/user/gen3-client/#3-upload-data-files
              - name: Download Single Data File
                link: /resources/user/gen3-client/#4-download-a-single-data-file-using-a-guid
              - name: Download Multiple Data Files
                link: /resources/user/gen3-client/#5-multiple-file-download-with-manifest
              - name: Generate a Metadata Submission TSV (Deprecated)
                link: /resources/user/gen3-client/#6-generate-a-metadata-submission-tsv-deprecated
              - name: Upload Single Data File
                link: /resources/user/gen3-client/#7-how-to-upload-a-single-data-file-using-a-guid
              - name: Upload Multiple Data Files
                link: /resources/user/gen3-client/#8-how-to-upload-multiple-data-files-using-a-manifest
              - name: Quick Start for Experienced Users or Cheat Sheet
                link: /resources/user/gen3-client/#9-quick-start-for-experienced-users-or-cheat-sheet
              - name: Working from the Command-line
                link: /resources/user/gen3-client/#10-working-from-the-command-line
          - name: Data Dictionary
            link: /resources/user/dictionary/
            submenu:
              - name: Understanding Data Representation in Gen3
                link: /resources/user/dictionary/#understanding-data-representation-in-gen3
              - name: Understanding the Gen3 Data Dictionary and Model
                link: /resources/user/dictionary/#understanding-the-gen3-data-dictionary-and-model
              - name: Data Dictionary Viewer
                link: /resources/user/dictionary/#data-dictionary-viewer
          - name: Managing Timepoints
            link: /resources/user/manage-submission/
          - name: Using the API
            link: /resources/user/using-api/
            submenu:
              - name: What Does the API Do
                link: /resources/user/using-api/#what-does-the-api-do
              - name: Credentials to send API requests
                link: /resources/user/using-api/#credentials-to-send-api-requests
              - name: Querying and Downloading Metadata using the API
                link: /resources/user/using-api/#querying-and-downloading-metadata-using-the-api
          - name: Query the Data
            link: /resources/user/query-data/
            submenu:
              - name: Graph Model
                link: /resources/user/query-data/#graph-model
              - name: Flat Model
                link: /resources/user/query-data/#flat-model
  faqMenu:
    title: FAQ
    content:
      - category: FAQ
        content:
          - name: Compose Services
            link: /resources/faq#compose-services
          - name: Cloud Automation
            link: /resources/faq#cloud-automation
          - name: Data Dictionary
            link: /resources/faq#data-dictionary

  featuresMenu:
    title: Gen3 Features
    content:
      - category: Gen3 Features
        content:
          - name: Dictionary
            link: /resources/gen3-features#dictionary
          - name: Metadata
            link: /resources/gen3-features#metadata
          - name: Data files
            link: /resources/gen3-features#data-files
          - name: Data exploration and analysis
            link: /resources/gen3-features#data-exploration-and-analysis
          - name: Access management and security
            link: /resources/gen3-features#access-management-and-security
          - name: Automation
            link: /resources/gen3-features#automation
