baseURL: http://gen3.org/
languageCode: en-us
title: Welcome to Gen3
SectionPagesMenu: mainmenu

menu: 
  mainmenu:
    - identifier: about
      name: About
      url: /
      weight: 10
    - identifier: products
      name: Products
      url: /products/
      weight: 20
    - identifier: get-started
      name: Get Started
      url: /get-started/
      hasChildren: true
      weight: 30
    - identifier: get-started/set-up
      name: Set up Gen3
      url: /get-started#set-up
      parent: get-started
      weight: 301
    - identifier: get-started/submit-data
      name: Submit Metadata&Data
      url: /get-started#submit-data
      parent: get-started
      weight: 302
    - identifier: get-started/access-data
      name: Acess Metadata&Data
      url: /get-started#access-data
      parent: get-started
      weight: 303
    - identifier: get-started/build-app
      name: Build Apps on Gen3
      url: /get-started#build-app
      parent: get-started
      weight: 304
    - identifier: resources
      name: Resources
      url: /resources/
      hasChildren: true
      weight: 40
    - identifier: /resources/user
      name: Gen3 User Guide
      url: /resources/user/
      parent: resources
      weight: 401
    - identifier: /resources/developer
      name: Gen3 Developer
      url: /resources/developer/
      parent: resources
      weight: 402
    - identifier: /resources/operator
      name: Gen3 Operator - Set up Gen3
      url: /resources/operator/
      parent: resources
      weight: 403
    - identifier: community
      name: Community
      url: /community/
      hasChildren: true
      weight: 50
    - identifier: /community/forums
      name: Forums
      url: https://forums.gen3.org/
      parent: community
      weight: 501
    - identifier: /community/medium
      name: Medium
      url: /community/medium/
      parent: community
      weight: 502
  footermenu1:
    - identifier: gen3
      name: Gen3
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /
      weight: 2
    - identifier: community
      name: Community
      url: /community
      weight: 3
    - identifier: why
      name: Why Gen3
      url: /products
      weight: 4
    - identifier: demo
      name: Demo
      url: https://nci-crdc-demo.datacommons.io/
      weight: 5
    - identifier: media
      name: Media
      url: /community
      weight: 6
  footermenu2:
    - identifier: run-commons
      name: Run a Gen3 commons
      url: /resources/operator
      weight: 1
    - identifier: submit-data
      name: Submit data to a commons
      url: /resources/user
      weight: 2
    - identifier: access-data
      name: Access data in a commons
      url: /resources/user
      weight: 3
    - identifier: build-app
      name: Build an app for Gen3
      url: /resources/developer
      weight: 4
params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  logo:
    src: /img/logos/gen3-dark.svg
    alt: Gen3 Data Commons Logo
  mobileLogo: 
    src: /img/logos/gen3.png
    alt: Gen3 Data Commons Logo
  icons:
    cross:
      src: /img/icons/x.svg
    toggleDown:
      src: /img/icons/toggle-down.svg
    toggleRight:
      src: /img/icons/toggle-right.svg
    menu: 
      src: /img/icons/menu.svg
    externalLink:
      src: /img/icons/external-link.svg
  submenu:
    - identifier: /resources/user
      name: Gen3 User Guide
      parent: resources
      url: /resources/user/
    - identifier: /resources/developer
      name: Gen3 Developer
      parent: resources
      url: /resources/developer/
    - identifier: /resources/operator
      name: Gen3 Operator - Set up Gen3
      parent: resources
      url: /resources/operator/
  developerMenu:
    title: Gen3 Developers Content
    content:
      - category: Gen3 Technology
        content:
          - name: Technique Intro
            link: /resources/developer/
          - name: Micro services
            link: /resources/developer/micro-service/
      - category: Tutorials
        content: 
          - name: Build Apps on Gen3
            link: /resources/developer/build-app/
            submenu:
              - name: 1. Authentication
                link: /resources/developer/build-app/#1-authentication
              - name: 2. GraphQL Queries
                link: /resources/developer/build-app/#2-graphql-queries
              - name: 3. GraphQL Queries You Want To Run
                link: /resources/developer/build-app/#3-graphql-queries-you-want-to-run
              - name: 4. Retrieve The Dictionary JSON Schema
                link: /resources/developer/build-app/#4-retrieve-the-dictionary-json-schema


  