baseURL: http://{BASE_URL}/
languageCode: en-us
title: Welcome to Gen3
SectionPagesMenu: mainmenu

# for local testing if using Hugo > 0.60.0
# see https://gohugo.io/news/0.60.0-relnotes/
markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  mainmenu:
    - identifier: about
      name: About
      url: /
      hasChildren: true
      weight: 10
    - identifier: powered-by-gen3
      name: Powered by Gen3
      url: /powered-by-gen3
      parent: about
      weight: 101
    - identifier: products
      name: Products
      url: /products/
      hasChildren: true
      weight: 20
    - identifier: products/data-ecosystems
      name: Data Ecosystems
      url: /products/data-ecosystems
      parent: products
      weight: 201
    - identifier: products/framework-services
      name: Framework Services
      url: /products/framework-services
      parent: products
      weight: 202
    - identifier: products/data-commons
      name: Data Commons
      url: /products/data-commons
      parent: products
      weight: 203
    - identifier: products/workspaces
      name: Workspaces
      url: /products/workspaces
      parent: products
      weight: 204
    - identifier: get-started
      name: Get Started
      url: /get-started/
      hasChildren: true
      weight: 30
    - identifier: get-started/set-up
      name: Set up Gen3
      url: /resources/operator/index.html
      parent: get-started
      weight: 301
    - identifier: get-started/submit-data
      name: Submit Metadata & Data
      url: /resources/user/submit-data
      parent: get-started
      weight: 302
    - identifier: get-started/access-data
      name: Access and Explore Metadata and Data Files
      url: /resources/user/access-data
      parent: get-started
      weight: 303
    - identifier: get-started/build-app
      name: Build Apps on Gen3
      url: /resources/developer/build-app
      parent: get-started
      weight: 304
    - identifier: resources
      name: Resources
      url: /resources/
      hasChildren: true
      weight: 40
    - identifier: resources/gen3-features
      name: Gen3 Features
      url: /resources/gen3-features
      parent: resources
      weight: 401
    - identifier: resources/user
      name: Gen3 User Guide
      url: /resources/user/
      parent: resources
      weight: 402
    - identifier: resources/developer
      name: Gen3 Developer
      url: /resources/developer/
      parent: resources
      weight: 403
    - identifier: resources/operator
      name: Gen3 Operator - Set up Gen3
      url: /resources/operator/
      parent: resources
      weight: 404
    - identifier: resources/faq
      name: Frequently Asked Questions
      url: /resources/faq/
      parent: resources
      weight: 405
    - identifier: community
      name: Community
      url: /index.html
      hasChildren: true
      weight: 50
    - identifier: community/webinars
      name: Webinars
      url: /community/webinars
      parent: community
      weight: 500
    - identifier: community/forums
      name: Forums
      url: https://forums.gen3.org/
      parent: community
      weight: 501
    - identifier: community/slack
      name: Join us on Slack!
      url: https://docs.google.com/forms/d/e/1FAIpQLSczyhhOXeCK9FdVtpQpelOHYnRj1EAq1rwwnm9q6cPAe5a7ug/viewform
      parent: community
      weight: 501
    - identifier: community/github
      name: Gen3 on GitHub
      url: https://github.com/search?q=topic%3Agen3+org%3Auc-cdis&type=Repositories
      parent: community
      weight: 503
    # - identifier: /community/medium
    #   name: Medium
    #   url: /community/medium/
    #   parent: community
    #   weight: 502
  footermenu1:
    - identifier: about
      name: About
      url: /
      weight: 1
    - identifier: community
      name: Community
      url: https://forums.gen3.org/
      weight: 2
    - identifier: why
      name: Why Gen3
      url: /products/
      weight: 3
    - identifier: demo
      name: Demo
      url: https://gen3.datacommons.io
      weight: 4
    - identifier: media
      name: Media
      url: /
      weight: 5
  footermenu2:
    - identifier: powered-by-gen3
      name: Powered by Gen3
      url: /powered-by-gen3
      weight: 1
    - identifier: run-commons
      name: Run a Gen3 commons
      url: /resources/operator
      weight: 2
    - identifier: submit-data
      name: Submit data to a commons
      url: /resources/user
      weight: 3
    - identifier: access-data
      name: Access data in a commons
      url: /resources/user
      weight: 4
    - identifier: build-app
      name: Build an app for Gen3
      url: /resources/developer
      weight: 5
params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  logo:
    src: /img/logos/gen3_new_logo_white.svg
    alt: Gen3 Data Commons Logo
  mobileLogo:
    src: /img/logos/gen3_new_logo.png
    alt: Gen3 Data Commons Logo
  icons:
    cross:
      src: /img/icons/x.svg
    toggleDown:
      src: /img/icons/toggle-down.svg
    toggleRight:
      src: /img/icons/toggle-right.svg
    menu:
      src: /img/icons/menu.svg
    externalLink:
      src: /img/icons/external-link.svg
  submenu:
    - identifier: resources/gen3-features
      name: Gen3 Features
      parent: resources
      url: /resources/gen3-features
    - identifier: /resources/user
      name: Gen3 User Guide
      parent: resources
      url: /resources/user/
    - identifier: /resources/developer
      name: Gen3 Developer
      parent: resources
      url: /resources/developer/
    - identifier: /resources/operator
      name: Gen3 Operator - Set up Gen3
      parent: resources
      url: /resources/operator/
    - identifier: resources/faq
      name: Frequently Asked Questions
      parent: resources
      url: /resources/faq/
  developerMenu:
    title: Gen3 Developers Content
    content:
      - category: Gen3 Technology
        content:
          - name: Technical Intro
            link: /resources/developer/
            submenu:
              - name: Terminology
                link: /resources/developer/#terminology
              - name: Data management
                link: /resources/developer/#data-management
              - name: Workspace Systems
                link: /resources/developer/#workspace-systems
          - name: Microservices
            link: /resources/developer/microservice/
      - category: Tutorials
        content:
          - name: Developer Introduction
            link: /resources/developer/dev-introduction/
            submenu:
              - name: General Development Philosophy
                link: /resources/developer/dev-introduction/#general-development-philosophy
              - name: GitHub Usage
                link: /resources/developer/dev-introduction/#github-usage
              - name: Kubernetes
                link: /resources/developer/dev-introduction/#kubernetes
              - name: Logging
                link: /resources/developer/dev-introduction/#logging
              - name: Python
                link: /resources/developer/dev-introduction/#python
              - name: Go
                link: /resources/developer/dev-introduction/#go
              - name: JavaScript
                link: /resources/developer/dev-introduction/#javascript
              - name: Licensing and Attribution
                link: /resources/developer/dev-introduction/#licensing-and-attribution
          - name: Build Apps on Gen3
            link: /resources/developer/build-app/
            submenu:
              - name: 1. Authentication
                link: /resources/developer/build-app/#1-authentication
              - name: 2. GraphQL Queries
                link: /resources/developer/build-app/#2-graphql-queries
              - name: 3. GraphQL Queries You Want To Run
                link: /resources/developer/build-app/#3-graphql-queries-you-want-to-run
              - name: 4. Retrieve The Dictionary JSON Schema
                link: /resources/developer/build-app/#4-retrieve-the-dictionary-json-schema
          - name: Gen3 Queries
            link: /resources/developer/flat-model-api/
  operatorMenu:
    title: Gen3 Operators
    content:
      - category: Running Commons
        content:
          - name: Compose-Services
            link: /resources/operator/#1-compose-services
          - name: Cloud Automation
            link: /resources/operator/#2-cloud-automation
          - name: Creating a New Data Dictionary
            link: /resources/operator/#3-creating-a-new-data-dictionary
          - name: Dictionary Update Documentation
            link: /resources/operator/#4-dictionary-update-documentation
          - name: Authentication Methods
            link: /resources/operator/#5-authentication-methods
          - name: Programs and Projects
            link: /resources/operator/#6-programs-and-projects
          - name: How to Upload and Control File Access via authz
            link: /resources/operator/#7-how-to-upload-and-control-file-access-via-authz
          - name: ETL and Data Explorer Configurations
            link: /resources/operator/#8-etl-and-data-explorer-configurations

  userMenu:
    title: Gen3 Users
    content:
      - category: Users
        content:
          - name: User Guide Overview
            link: /resources/user
          - name: Access and Explore Metadata/Data Files
            link: /resources/user/access-data/
            submenu:
              - name: Access Data from the Data Commons Website
                link: /resources/user/access-data/#the-data-commons-website
              - name: Access Data using the API
                link: /resources/user/access-data/#access-data-using-the-api
          - name: Analyze Data
            link: /resources/user/analyze-data/
            submenu:
              - name: Launch Workspace
                link: /resources/user/analyze-data/#1-launch-workspace
              - name: Getting Files into the Gen3 Workspace
                link: /resources/user/analyze-data/#2-getting-files-into-the-gen3-workspace
              - name: Working with the proxy and whitelists
                link: /resources/user/analyze-data/#3-working-with-the-proxy-and-whitelists
              - name: Using the Gen3 Python SDK
                link: /resources/user/analyze-data/#4-using-the-gen3-python-sdk
              - name: Jupyter Notebook Demos
                link: /resources/user/analyze-data/#5-jupyter-notebook-demos
          - name: Guide for Data Contributions
            link: /resources/user/submit-data/
            submenu:
              - name: Prepare Project in Submission Portal
                link: /resources/user/submit-data/#1-prepare-project-in-submission-portal
              - name: Upload Data Files to Object Storage
                link: /resources/user/submit-data/#2-upload-data-files-to-object-storage
              - name: Map Uploaded Files to a Data File Node
                link: /resources/user/submit-data/#3-map-uploaded-files-to-a-data-file-node
              - name: Submit Additional Project Metadata
                link: /resources/user/submit-data/#4-submit-additional-project-metadata
              - name: Link Data File Records to their Metadata Records
                link: /resources/user/submit-data/#5-link-files-to-their-metadata
          - name: TSV Formatting and Templates
            link: /resources/user/template-tsvs/
            submenu:
              - name: TSV Formatting Checklist
                link: /resources/user/template-tsvs/#tsv-formatting-checklist
              - name: Notes about TSV Formatting
                link: /resources/user/template-tsvs/#notes-about-tsv-formatting
              - name: Template TSVs for Metadata Submission
                link: /resources/user/template-tsvs/#template-tsvs-for-metadata-submission
          - name: Upload/Download Data Files Using the Gen3-Client
            link: /resources/user/gen3-client/
            submenu:
              - name: Installation Instructions
                link: /resources/user/gen3-client/#1-installation-instructions
              - name: Configure a Profile
                link: /resources/user/gen3-client/#2-configure-a-profile-with-credentials
              - name: Upload Data Files
                link: /resources/user/gen3-client/#3-upload-data-files
              - name: Download Single Data File
                link: /resources/user/gen3-client/#4-download-a-single-data-file-using-a-guid
              - name: Download Multiple Data Files
                link: /resources/user/gen3-client/#5-multiple-file-download-with-manifest
              - name: Generate a Metadata Submission TSV
                link: /resources/user/gen3-client/#6-generate-a-metadata-submission-tsv
              - name: Upload Single Data File
                link: /resources/user/gen3-client/#7-how-to-upload-a-single-data-file-using-a-guid
              - name: Upload Multiple Data Files
                link: /resources/user/gen3-client/#8-how-to-upload-multiple-data-files-using-a-manifest
              - name: Quick Start for Experienced Users or Cheat Sheet
                link: /resources/user/gen3-client/#9-quick-start-for-experienced-users-or-cheat-sheet
              - name: Working from the Command-line
                link: /resources/user/gen3-client/#10-working-from-the-command-line
          - name: Data Dictionary
            link: /resources/user/dictionary/
            submenu:
              - name: Understanding Data Representation in Gen3
                link: /resources/user/dictionary/#understanding-data-representation-in-gen3
              - name: Understanding the Gen3 Data Dictionary and Model
                link: /resources/user/dictionary/#understanding-the-gen3-data-dictionary-and-model
              - name: Data Dictionary Viewer
                link: /resources/user/dictionary/#data-dictionary-viewer
          - name: Managing Timepoints
            link: /resources/user/manage-submission/
          - name: Using the API
            link: /resources/user/using-api/
            submenu:
              - name: What Does the API Do
                link: /resources/user/using-api/#what-does-the-api-do
              - name: Credentials to send API requests
                link: /resources/user/using-api/#credentials-to-send-api-requests
              - name: Querying and Downloading Metadata using the API
                link: /resources/user/using-api/#querying-and-downloading-metadata-using-the-api
          - name: Query the Data
            link: /resources/user/query-data/
            submenu:
              - name: Graph Model
                link: /resources/user/query-data/#graph-model
              - name: Flat Model
                link: /resources/user/query-data/#flat-model
  faqMenu:
    title: FAQ
    content:
      - category: FAQ
        content:
          - name: Compose Services
            link: /resources/faq#compose-services
          - name: Cloud Automation
            link: /resources/faq#cloud-automation
          - name: Data Dictionary
            link: /resources/faq#data-dictionary

  featuresMenu:
    title: Gen3 Features
    content:
      - category: Gen3 Features
        content:
          - name: Dictionary and structured data
            link: /resources/gen3-features#dictionary-and-structured-data
          - name: Data files
            link: /resources/gen3-features#data-files
          - name: Data exploration and analysis
            link: /resources/gen3-features#data-exploration-and-analysis
          - name: Access management and security
            link: /resources/gen3-features#access-management-and-security
          - name: Automation
            link: /resources/gen3-features#automation
